### ISSUE TITLE
predict with cv option

### ISSUE THREAD

**Issue by markeschaffer** [aahrens1/pystacked#13]
predict with the cv option seems to create the same predicted values as without the cv option.

also, predict+dv creates predicted values for the holdout sample but such values shouldn't exist.

**Comment by aahrens1** [comment]
should work (again)

**Comment by markeschaffer** [comment]
predict with cv + transform options now fails with an error:

```
. predict double ps_yhat_cv, xb cv transform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 40, in post_prediction
  File "C:\LocalStore\ecomes\Stata16\ado\base\py\sfi.py", line 411, in addVarDouble
    return _stp._st_addvardouble(name)
SystemError: failed to add a variable of type double to the current Stata dataset
```
To replicate, use the (updated) cert script for stacking, cs_stacking.do.

**Comment by markeschaffer** [comment]
predict with cv + transform options now fails with an error:

```
. predict double ps_yhat_cv, xb cv transform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 40, in post_prediction
  File "C:\LocalStore\ecomes\Stata16\ado\base\py\sfi.py", line 411, in addVarDouble
    return _stp._st_addvardouble(name)
SystemError: failed to add a variable of type double to the current Stata dataset
```
To replicate, use the (updated) cert script for stacking, cs_stacking.do.

**Comment by aahrens1** [comment]
you should only specify one of the three options.

**Comment by markeschaffer** [comment]
You mean either cv or transform but not both, I think.  (Omitting the default xb doesn't do anything.)

This is stacking.ado's behaviour:

xb+cv: stacked cross-validated predictions
xb+cv+transform: cross-validated predictions for the separate learners

 I think this is worth doing - the stacked cross-validated predictions are useful.  They are (I think, or should be) the fitted values from the NNLS step.

**Comment by aahrens1** [comment]
cv gives the cross-validated predictions per base learner. 

transform gives the predictions per base learner (fitted on whole sample).

xb gives the stacking predicted values. xb is the default.  

cv+resid, for example, doesn't work and I don't think there is a need to implement it. I wouldn't prioritise stacked cross-validated predictions either.

**Comment by markeschaffer** [comment]
Can you change the syntax so that cv+transform mimics the behaviour of stacking.ado and gives the cross-validated predictions per base learner?  (And cv on its own causes an error.)

It will be confusing to users of both otherwise (it was to me!).

**Comment by markeschaffer** [comment]
BTW, in the stacking.ado RMSPE table there are now 4 columns, for (1) weights, (2) in-sample, fitted on the training sample, (3) cross-validated, for the training sample, and (4) holdout sample.  The stacked CV predictions go in column (3) and row (1) (the stacking row).

**Comment by aahrens1** [comment]
The actual confusing thing is the name "transform" which we should rename to "basexb" (for base learner predictions) or "base" (for _by_ base learner). "transform" was just the name from the sklearn function, which I shouldn't have adopted. You can make the changes. I have no strong views on this.

**Comment by aahrens1** [comment]
Sure

**Comment by markeschaffer** [comment]
Implemented in pystacked, along with cv option for tables and graphs for regression problems.

Have not yet implemented for classification problems.

stacked cv (=weighted cv predictions) is implemented in pystacked for the purposes of graphing and the rmspe table, but is not (yet) supported in pystacked_p.ado, so maybe leave this issue open for that as well.

**Comment by aahrens1** [comment]
Thanks. Can you edit the help file so that we document the current behavior?

**Comment by markeschaffer** [comment]
Will do, after all the changes are done. Still have to do/check classification problems.

**Comment by markeschaffer** [comment]
Just pushed to github. The stacked cross-validated predictions, and the cv residuals, are implemented in pystacked (needed for the table and graphs) and not in pystacked.ado.

No cert file yet. Maybe use the stacking cert file as the basis? So they cross-certify each other.

**Comment by aahrens1** [comment]
There is one issue: not all final estimators support cvalid+basexb. It only works for NNLS and singlebest at the moment. I would have to figure out how it would work for others (e.g. ridge) but not sure it's worth the effort because it looks a bit tricky. Can we add an exception where the CV row is just a column of NAs for other final estimators? This currently returns an error:
```
insheet using "/Users/kahrens/Dropbox (PP)/ddml/Data/housing.csv", ///
	clear comma
	
gen u = runiform()
egen fid = cut(u), at(0,.25,.5,.75,1) icodes
 
replace medv =medv>20

pystacked medv crim-lstat if _n<=200, type(reg) m(ols ridgecv gradboost lassocv) foldvar(fid) finalest(ridge)
*predict b, basexb cvalid
pystacked, table holdout
```

**Comment by markeschaffer** [comment]
Now fixed:
1. pystacked.ado returns all missings for CV predicted values if unavailable.
2. pystacked_p.ado issues a warning if CV predicted values unavailable.
