### ISSUE TITLE
When using the rf method of pystacked, how to specify the parameters of random forest?

### ISSUE THREAD

**Issue by marshzhao** [aahrens1/pystacked#30]
When using the rf method of pystacked, how to specify the parameters of random forest, such as n_estimators and max_features?

For example, how to specify the n_estimators and max_features parameters in this code?
ddml E[Y|X]: pystacked $Y $X, type(class) method(rf)

Thanks for your help!

**Comment by aahrens1** [comment]
Two  options:

```
net install pystacked, from(https://raw.githubusercontent.com/aahrens1/pystacked/main) replace

insheet using                                           ///
		/Users/kahrens/MyProjects/pystacked/data/housing.csv,   ///
		clear comma 
 
pystacked medv crim-lstat || m(rf) opt(n_estimators(100)), type(reg) showc

pystacked medv crim-lstat, m(rf) cmdopt1(n_estimators(100)) type(reg) showc

```

**Comment by marshzhao** [comment]
Thank you very much! I have successfully resolved the issue using your advice.
