### ISSUE TITLE
pystacked incorrectly (?) detecting change in data in memory

### ISSUE THREAD

**Issue by markeschaffer** [aahrens1/pystacked#9]
The new stacking command can use pystacked as a front-end for separate calls to pystacked.

The help file for stacking has an example. The problem is that it works only once. If the same stacking command is re-executed, the pystacked error message about detecting a change in data in memory appears. The workaround to fix it is to clear Stata and reload the data etc.

The following lines will trigger the error.

```
insheet using https://statalasso.github.io/dta/housing.csv, clear
stacking medv if _n<=200, estring(pystacked medv zn-rad, type(regress) methods(ols) || pystacked medv zn-rad, type(regress) methods(lassoic)) kfolds(2) norandom
stacking medv if _n<=200, estring(pystacked medv zn-rad, type(regress) methods(ols) || pystacked medv zn-rad, type(regress) methods(lassoic)) kfolds(2) norandom
```

**Comment by aahrens1** [comment]
I get `invalid syntax` when I run this. 

```
. insheet using https://statalasso.github.io/dta/housing.csv, clear
(14 vars, 506 obs)

. stacking medv if _n<=200, estring(pystacked medv zn-rad, type(regress) methods(ols) || pystacked medv zn-rad,
>  type(regress) methods(lassoic)) kfolds(2) norandom
invalid syntax
r(198);
```

`pystacked` doesn't allow you to change the data in memory between estimation and `predict`. Is this what is causing the error?

**Comment by markeschaffer** [comment]
Weird - runs fine just once on my machine. Can you send a trace?

But I think I know the answer. stacking overwrites some saved variables if they already exist. Can you add an option to pystacked that drops this check?

**Comment by markeschaffer** [comment]
Btw I am mostly free today if any debugging requires a Teams or Zoom meeting.

**Comment by aahrens1** [comment]
There is an undocumented `force` option. Maybe have a check how we do it in the cross-fitting implementation where we essentially do the same?

Tracing ends with 
```
    = ereturn matrix mse_folds =__000004
    - ereturn matrix N_folds_list =`N_folds_list'
    = ereturn matrix N_folds_list =__000005
    - ereturn matrix mse_folds_list =`mse_folds_list'
    = ereturn matrix mse_folds_list =__000006
    - ereturn matrix N_list =`N_list'
    = ereturn matrix N_list =__000007
    - ereturn matrix mse_list =`mse_list'
    = ereturn matrix mse_list =__000008
    - ereturn scalar cvoos =`cvoos'
    = ereturn scalar cvoos =
invalid syntax
    -------------------------------------------------------------------------------- end stacking._stacking ---
    }
  -------------
```

**Comment by markeschaffer** [comment]
Will check the force option etc.

You need to update stacking - I changed cvoos to cvalid yesterday.

**Comment by aahrens1** [comment]
Where does stacking.ado live now? I am using the latest version on ddml.

**Comment by markeschaffer** [comment]
This is weird - my desktop github agrees that I pushed it last night (7 hours ago) but it doesn't seem to be reflected in the repository on github.

**Comment by markeschaffer** [comment]
Correction - it's there (now, anyway).

**Comment by markeschaffer** [comment]
force option doesn't help - it's an option for predict, and the call to predict in stacking is hard-coded.

But I think I see what's going on. The issue is that stacking needs to call the base learners to get their predicted values and save them. If you did this on the fly when predict+transform is called, you'd get different predicted values each time if the learner has any randomisation. To mimic pystacked, stacking creates and saves these at estimation time. Might be an easy fix.

**Comment by aahrens1** [comment]
No chance in pystacked required?

**Comment by markeschaffer** [comment]
I fixed it in stacking - required a minor reordering of some code. Update should be on git now. No changes to pystacked required.

stacking should go in another repository. Do you want to create one (alongside pystacked, pylearn2, etc.) and I'll move it there?

**Comment by aahrens1** [comment]
Sure, I will close. I will close this issue.
